---
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npm test  
after_success:
  - coveralls --exclude __tests__/ --gcov-options '\-lpbc'
